services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - rp_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  rp_pg_data: