// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID             uuid.UUID
	HashedPassword string
	Name           string
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
