// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Resume struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Title       string
	Description string
	CompanyName string
	Feedback    sql.NullString
	ImagePath   string
	PdfPath     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID             uuid.UUID
	HashedPassword string
	Name           string
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
